import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/app/_components/header'
import { cn } from '@/lib/utils'

import './globals.css'
import Navbar from './_components/nav-bar'

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Go Dutch',
  // description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body
        className={cn('flex h-full min-h-screen flex-col', fontSans.className)}
      >
        <Header />
        <div className="flex w-full flex-1 flex-grow flex-col md:flex-row">
          <Navbar />
          <main className="flex flex-grow flex-col items-center justify-between *:w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
